/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Advanced settings": {                           "en": "Advanced settings",                               "de": "Erweiterte Einstellungen",                        "ru": "Расширенные настройки",                           "pt": "Configurações avançadas",                         "nl": "Geavanceerde instellingen",                       "fr": "Réglages avancés",                                "it": "Impostazioni avanzate",                           "es": "Ajustes avanzados",                               "pl": "Zaawansowane ustawienia",                         "zh-cn": "高级设置"},
    "Altitude": {                                    "en": "Altitude",                                        "de": "Höhe",                                            "ru": "Высота",                                          "pt": "Altitude",                                        "nl": "Hoogte",                                          "fr": "Altitude",                                        "it": "Altitudine",                                      "es": "Altitud",                                         "pl": "Wysokość",                                        "zh-cn": "高度"},
    "Comfort settings": {                            "en": "Comfort settings",                                "de": "Komforteinstellungen",                            "ru": "Настройки комфорта",                              "pt": "Configurações de conforto",                       "nl": "Comfort instellingen",                            "fr": "Paramètres de confort",                           "it": "Impostazioni comfort",                            "es": "Configuraciones de confort",                      "pl": "Ustawienia komfortu",                             "zh-cn": "舒适度设置"},
    "Compact": {                                     "en": "Compact",                                         "de": "Kompakt",                                         "ru": "Компактный",                                      "pt": "Compactar",                                       "nl": "Compact",                                         "fr": "Compact",                                         "it": "Compatto",                                        "es": "Compacto",                                        "pl": "Kompaktowy",                                      "zh-cn": "袖珍的"},
    "Language": {                                    "en": "Language",                                        "de": "Sprache",                                         "ru": "Язык",                                            "pt": "Língua",                                          "nl": "Taal",                                            "fr": "La langue",                                       "it": "linguaggio",                                      "es": "Idioma",                                          "pl": "Język",                                           "zh-cn": "语"},
    "Latitude": {                                    "en": "Latitude",                                        "de": "Breitengrad",                                     "ru": "Широта",                                          "pt": "Latitude",                                        "nl": "Breedtegraad",                                    "fr": "Latitude",                                        "it": "Latitudine",                                      "es": "Latitud",                                         "pl": "Szerokość",                                       "zh-cn": "纬度"},
    "Location": {                                    "en": "Location",                                        "de": "Standort",                                        "ru": "Место нахождения",                                "pt": "Localização",                                     "nl": "Plaats",                                          "fr": "Emplacement",                                     "it": "Posizione",                                       "es": "Localización",                                    "pl": "Lokalizacja",                                     "zh-cn": "地点"},
    "Longitude": {                                   "en": "Longitude",                                       "de": "Längengrad",                                      "ru": "Долгота",                                         "pt": "Longitude",                                       "nl": "Lengtegraad",                                     "fr": "Longitude",                                       "it": "Longitudine",                                     "es": "Longitud",                                        "pl": "Długość geograficzna",                            "zh-cn": "经度"},
    "Options": {                                     "en": "Options",                                         "de": "Einstellungen",                                   "ru": "Настройки",                                       "pt": "Opções",                                          "nl": "opties",                                          "fr": "Options",                                         "it": "Opzioni",                                         "es": "Opciones",                                        "pl": "Opcje",                                           "zh-cn": "选项"},
    "Send Translations": {                           "en": "Send missing translations to iobroker.net",       "de": "Fehlende Übersetzungen an iobroker.net senden",   "ru": "Отправить недостающие переводы на iobroker.net",  "pt": "Envie traduções faltando para iobroker.net",      "nl": "Verzend ontbrekende vertalingen naar iobroker.net", "fr": "Envoyer des traductions manquantes à iobroker.net", "it": "Invia traduzioni mancanti a iobroker.net",        "es": "Envía traducciones faltantes a iobroker.net",     "pl": "Wyślij brakujące tłumaczenia do iobroker.net",    "zh-cn": "将丢失的翻译发送到 iobroker.net"},
    "uses system config if empty": {                 "en": "uses system config if empty",                     "de": "verwendet Systemkonfiguration, wenn leer",        "ru": "использует системную конфигурацию, если она пуста", "pt": "usa a configuração do sistema se estiver vazio",  "nl": "gebruikt systeemconfiguratie indien leeg",        "fr": "utilise la configuration système si vide",        "it": "usa la configurazione di sistema se vuoto",       "es": "usa la configuración del sistema si está vacío",  "pl": "używa konfiguracji systemu, jeśli jest pusty",    "zh-cn": "如果为空，则使用系统配置"},
};